package model;

// Generated 2015. 2. 11 ¿ÀÈÄ 7:13:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * DeviceInfo generated by hbm2java
 */
@Entity
@Table(name = "device_info", catalog = "ubiq")
public class DeviceInfo implements java.io.Serializable {

	private Integer deviceid;
	private String nickName;
	private String pin;
	private String deviceType;
	private String ip;
	private String status;
	private Set<UserInfo> userInfos = new HashSet<UserInfo>(0);

	public DeviceInfo() {
	}

	public DeviceInfo(String nickName, String pin, String deviceType,
			String ip, String status, Set<UserInfo> userInfos) {
		this.nickName = nickName;
		this.pin = pin;
		this.deviceType = deviceType;
		this.ip = ip;
		this.status = status;
		this.userInfos = userInfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "deviceid", unique = true, nullable = false)
	public Integer getDeviceid() {
		return this.deviceid;
	}

	public void setDeviceid(Integer deviceid) {
		this.deviceid = deviceid;
	}

	@Column(name = "nick_name", length = 45)
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "pin", length = 45)
	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	@Column(name = "device_type", length = 45)
	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	@Column(name = "ip", length = 45)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_info_has_device_info", catalog = "ubiq", joinColumns = { @JoinColumn(name = "device_info_deviceid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "user_info_userid", nullable = false, updatable = false) })
	public Set<UserInfo> getUserInfos() {
		return this.userInfos;
	}

	public void setUserInfos(Set<UserInfo> userInfos) {
		this.userInfos = userInfos;
	}

}
